name: sbig_app
description: SBI General Insurance application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+4

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # Database
  # sqflite: ^1.1.6
  # Flutter plugin for getting commonly used locations on the Android & iOS file systems, such as the temp and app data directories.
  path_provider: ^1.2.0
  # Reactive Programming
  rxdart: ^0.22.1+1
  # Internationalizing
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  # Shared Preferences
  shared_preferences: ^0.5.6
  # Path drawing
  # path_drawing: ^0.4.0
  # Shimmer loading effect
  shimmer: ^1.0.0
  # Image Picker
  # image_picker: ^0.6.1+4
  # Toast
  fluttertoast: ^3.1.3
  # Permissions handler
  permission_handler: ^4.4.0+hotfix.2
  # Networking
  dio: ^3.0.3
  # Image Cropping
  # image_cropper: ^1.1.0
  # Share Action
  # share: ^0.6.3
  # Swipe Pages
  flutter_swiper: ^1.1.6
  # Dotted Border
  dotted_border: ^1.0.3
  # Date and number formatting
  # SMS with message body
  flutter_sms: ^1.1.0
  #Singleton class
  get_it: ^3.0.3
  intl: ^0.16.0
  # Keyboard listener
  keyboard_visibility: ^0.5.6
  # Date Picker
  flutter_rounded_date_picker: ^0.3.0
  # Internet connectivity
  connectivity: 0.4.5+3
  # CALL and MAIL
  url_launcher: ^5.2.5
  flutter_gifimage: ^1.0.0

  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.10
  firebase_crashlytics: ^0.1.1+2

  #Get app and device info
  package_info: ^0.4.0+13
  device_info: ^0.4.1+4

  #payment gateway
  razorpay_flutter: ^1.1.2

  #to get City and State information form lat long
  geolocator: ^5.3.0
  location: ^2.5.0

 # another option for webview
  flutter_webview_plugin:
    path: plugins/flutter_webview_plugin
 # In App webview
  flutter_inappwebview: ^2.1.0+1

  open_file: ^2.1.1

  #Root checker
  trust_fall: ^1.0.4

  # Flip card
  flip_card: ^0.4.4

  autocomplete_textfield: ^1.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/background/
    - assets/icons/
    - assets/docprime_disclaimer.txt

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Effra
      fonts:
        - asset: fonts/Effra-Regular.ttf
          style: normal
        - asset: fonts/Effra-Medium.ttf
          weight: 500
        - asset: fonts/Effra-Medium.ttf
          weight: 600
        - asset: fonts/Effra-Bold.ttf
          weight: 700
        - asset: fonts/Effra-Bold.ttf
          weight: 900
    - family: BradleyHand
      fonts:
        - asset: fonts/BradleyHand-Bold.ttf

    - family: Effra-Light
      fonts:
        - asset: fonts/Effra-Light.ttf
          weight: 700
#  fonts:
#  - family: Swiss
#    fonts:
#      - asset: fonts/Swiss-Medium.otf
#        style: normal
#      - asset: fonts/Swiss-Italic.ttf
#        style: italic
##      - asset: fonts/Swiss-Light.ttf
##        weight: 100
#      - asset: fonts/Swiss-Roman.ttf
#        weight: 500
#      - asset: fonts/Swiss-Bold.ttf
#        weight: 700
#      - asset: fonts/Swiss-Heavy.ttf
#        weight: 900
#  - family: BradleyHand
#    fonts:
#      - asset: fonts/BradleyHand-Bold.ttf
#
#  - family: Swiss-Light
#    fonts:
#      - asset: fonts/Swiss-Light.ttf
#        weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
